[package]
name = "opensuite-docx"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
opensuite-opc = { path = "../opensuite-opc" }
opensuite-protocol = { path = "../opensuite-protocol" }
quick-xml = "0.37"
zip = { version = "2.2", default-features = false, features = ["deflate"] }

[dev-dependencies]

[lints]
workspace = true
