[package]
name = "opensuite"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
opensuite-docx = { path = "../../crates/opensuite-docx" }
opensuite-opc = { path = "../../crates/opensuite-opc" }
opensuite-protocol = { path = "../../crates/opensuite-protocol" }
serde_json = "1"

[lints]
workspace = true
